PYTHONPATH=. python text_classification/finetune_text_classification.py \
    --task 'text-classification' \
    --model 'damo/nlp_structbert_backbone_base_std' \
    --train_dataset_name 'clue' \
    --val_dataset_name 'clue' \
    --train_subset_name 'tnews' \
    --val_subset_name 'tnews' \
    --train_split 'train' \
    --val_split 'validation' \
    --first_sequence 'sentence' \
    --label label \
    --preprocessor 'sen-cls-tokenizer' \
    --use_model_config True \
    --max_epochs 12 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 32 \
    --eval_interval 100 \
    --eval_strategy by_step \
    --work_dir './tmp/structbert_1x32' \
    --train_data_worker 0 \
    --eval_data_worker 0 \
    --lr 1e-5 \
    --eval_metrics 'seq-cls-metric'